[package]
name = "ruku"
version = "0.1.0"
authors = ["joker666 <mr.k779@outlook.com>"]
description = "A tiny PaaS. Ruku allows you to do git push deployments to your own servers."
edition = "2021"
license = "MIT"
homepage = "https://github.com/Joker666/ruku"
repository = "https://github.com/Joker666/ruku"

[dependencies]
bollard = "0.16.1"
clap = { version = "4.5.7", features = ["derive"] }
cmd_lib = "1.9.4"
colored = "2.1.0"
dotenvy = "0.15.7"
envy = "0.4.2"
home = "0.5.9"
nixpacks = "1.24.1"
serde = { version = "1.0.203", features = ["derive"] }
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
